// OfficeAddin/05 Using modern JavaScript/Demos/01 Office Add-in using React/src/taskpane/components/Header.tsx
/*
 * Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
 * See LICENSE in the project root for license information.
 */

import * as React from 'react';

export interface HeaderProps {
  title: string;
}

export class Header extends React.Component<HeaderProps, any> {
  constructor(props, context) {
    super(props, context);
  }

  render() {
    return (
      <div className="ms-bgColor-greenDark header">
        <span className="ms-font-xxl ms-fontColor-white">{this.props.title}</span>
      </div>
    );
  }
}

// OfficeAddin/05 Using modern JavaScript/Demos/03 Office Add-in using VueJS/src/taskpane/components/HeaderComponent.vue
/* 
 * Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
 * See LICENSE in the project root for license information.
 */

<template>
    <div>
        <div class="ms-bgColor-greenDark header">
            <span class="ms-font-su ms-fontColor-white">{{title}}</span>
        </div>
        <div class="ms-MessageBanner" v-if="error">
            <div class="ms-MessageBanner-content" style="text-align: left; margin-left: 40px;">
                <div class="ms-MessageBanner-text ms-font-s-plus">
                    <div class="ms-MessageBanner-clipper">
                        <i class="ms-Icon ms-Icon--Error"></i>
                        <span style="vertical-align: top;">&nbsp;{{error}}</span>
                    </div>
                </div>
            </div>
            <button class="ms-MessageBanner-close" v-on:click="error = null;">
                <i class="ms-Icon ms-Icon--Clear"></i>
            </button>
        </div>
    </div>
</template>

<script lang="ts">
import * as Vue from "vue";
import Component from 'vue-class-component';

@Component({
    props: {
        title: String,
        error: String
    }
})
export default class headerComponent extends Vue {
    name: 'headerComponent';
    title: String;
    error: String;
}
</script>
