// OfficeAddin/05 Using modern JavaScript/Demos/01 Office Add-in using React/src/components/waiting.tsx
import * as React from 'react';
import { Overlay, Spinner, SpinnerSize } from 'office-ui-fabric-react';

export class Waiting extends React.Component<any, any> {
  constructor(props, context) {
    super(props, context);
  }

  render() {
    return (
      <Overlay isDarkThemed={true} className="overlay">
        <div className="spinner">
          <Spinner size={SpinnerSize.large} />
        </div>
      </Overlay>
    );
  }
}

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

// OfficeAddin/05 Using modern JavaScript/Demos/03 Office Add-in using VueJS/src/components/waiting.vue
<template>
<div>
    <div class="overlay"></div>
    <img class="spinner" src="/assets/spinner.gif"/>
</div>
</template>

<script lang="ts">
import Vue from 'vue';
import Component from 'vue-class-component';

@Component({})
export default class waiting extends Vue {
  name: 'waiting'
}
</script>

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.
