// OfficeAddin/05 Using modern JavaScript/Demos/02 Office Add-in using Angular/src/app/app.component.ts
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

import { Component, NgZone } from '@angular/core';
import * as OfficeHelpers from '@microsoft/office-js-helpers';
import { ExcelTableUtil } from './utils/excelTableUtil';

const ALPHAVANTAGE_APIKEY: string = '{{REPLACE_WITH_ALPHAVANTAGE_APIKEY}}';
const template = require('./app.component.html');

@Component({
    selector: 'app-home',
    template
})

export default class AppComponent {  
    symbols = [];
    error = null;
    waiting = false;
    zone = new NgZone({});
    
    tableUtil = new ExcelTableUtil('Portfolio', 'A1:H1', [
        'Symbol',
        'Last Price',
        'Timestamp',
        'Quantity',
        'Price Paid',
        'Total Gain',
        'Total Gain %',
        'Value'
    ]);

    constructor() {
        this.syncTable().then(() => {});
    }

    // Adds symbol
    addSymbol = async (symbol) => {
        this.waiting = true;
  
        // Get quote and add to Excel table
        this.getQuote(symbol).then((res) => {
            const data = [
                res['1. symbol'], //Symbol
                res['2. price'], //Last Price
                res['4. timestamp'], // Timestamp of quote,
                0, // quantity (manually entered)
                0, // price paid (manually entered)
                '=(B:B * D:D) - (E:E * D:D)', //Total Gain $
                '=H:H / (E:E * D:D) * 100', //Total Gain %
                '=B:B * D:D' //Value
            ];
            this.tableUtil.addRow(data).then(() => {
                this.symbols.unshift(symbol.toUpperCase());
                this.waiting = false;
            },
            (err) => {
                this.error = err;
            });
        },
        err => {
            this.error = err;
            this.waiting = false;
        });
    }

    // Delete symbol
    deleteSymbol = async (index) => {
        // Delete from Excel table by index number
        const symbol:string = this.symbols[index];
        this.waiting = true;
        this.tableUtil.getColumnData('Symbol').then(async (columnData:string[]) => {
            // Ensure the symbol was found in the Excel table
            if (columnData.indexOf(symbol) !== -1) {
                this.tableUtil.deleteRow(columnData.indexOf(symbol)).then(async () => {
                    this.symbols.splice(index, 1);
                    this.waiting = false;
                }, err => {
                    this.error = err;
                    this.waiting = false;
                });
            } else {
                this.symbols.splice(index, 1);
                this.waiting = false;
            }
        }, (err) => {
            this.error = err;
            this.waiting = false;
        });
    }

    // Refresh symbol
    refreshSymbol = async (index) => {
        // Refresh stock quote and update Excel table
        const symbol = this.symbols[index];
        this.waiting = true;
        this.tableUtil.getColumnData('Symbol').then(async (columnData:string[]) => {
            // Ensure the symbol was found in the Excel table
            const rowIndex = columnData.indexOf(symbol);
            if (rowIndex !== -1) {
                this.getQuote(symbol).then((res) => {
                    // "last trade" is in column B with a row index offset of 2 (row 0 + the header row)
                    this.tableUtil.updateCell(`B${rowIndex + 2}:B${rowIndex + 2}`, res['2. price']).then(async () => {
                        this.waiting = false;
                    }, (err) => {
                        this.error = err;
                        this.waiting = false;
                    });
                });
            } else {
                this.error = `${symbol} not found in Excel`;
                this.symbols.splice(index, 1);
                this.waiting = false;
            }
        }, (err) => {
            this.error = err;
            this.waiting = false;
        });
    }

    // Reads symbols from an existing Excel workbook and pre-populates them in the add-in
    syncTable = async () => {
        this.waiting = true;
        this.tableUtil.getColumnData('Symbol').then(async (columnData:string[]) => {
            this.symbols = columnData;
            this.waiting = false;
        }, (err) => {
            this.error = err;
            this.waiting = false;
        });
    }

    // Gets a quote by calling into the stock service
    getQuote = async (symbol) => {
        return new Promise((resolve, reject) => {
            const queryEndpoint = `https://www.alphavantage.co/query?function=BATCH_STOCK_QUOTES&symbols=${escape(symbol)}&interval=1min&apikey=${ALPHAVANTAGE_APIKEY}`;
  
            fetch(queryEndpoint).then((res) => {
                if (!res.ok) {
                    reject('Error getting quote');
                }
                return res.json();
            }).then((jsonResponse) => {
                const quote = jsonResponse['Stock Quotes'][0];
                resolve(quote);
            });
        });
    }
}
<!-- Copyright (c) Microsoft Corporation. All rights reserved.
     Licensed under the MIT License. -->
     
<div>
    <div *ngIf="waiting">
        <div class="overlay"></div>
        <img class="spinner" src="/assets/spinner.gif"/>
    </div>
    <div class="ms-bgColor-greenDark header">
        <span class="ms-font-su ms-fontColor-white">Excel Portfolio</span>
    </div>
    <div>
        <div class="ms-MessageBanner" *ngIf="error">
            <div class="ms-MessageBanner-content" style="text-align: left; margin-left: 40px;">
                <div class="ms-MessageBanner-text ms-font-s-plus">
                    <div class="ms-MessageBanner-clipper">
                        <i class="ms-Icon ms-Icon--Error"></i>
                        <span style="vertical-align: top;">&nbsp;{{error}}</span>
                    </div>
                </div>
            </div>
            <button class="ms-MessageBanner-close" (click)="error = null;">
                <i class="ms-Icon ms-Icon--Clear"></i>
            </button>
        </div>
        <div class="padding10">
            <div class="pct100 tbl-head">
                <span class="ms-font-l">Stock Symbols</span>
            </div>
            <div class="pct100">
                <input class="ms-TextField-field" #newSymbol (keyup.enter)="addSymbol(newSymbol.value); newSymbol.value = '';" placeholder="Enter a stock symbol (ex: MSFT)" />
            </div>
            <div class="pct100 itemRow" *ngFor="let symbol of symbols; let i = index" >
                <div class="left ms-font-l">{{symbol}}</div>
                <div class="right">
                    <div class="left icon" (click)="refreshSymbol(i)"><i class="ms-Icon ms-Icon--Refresh" aria-hidden="true"></i></div>
                    <div class="left icon" (click)="deleteSymbol(i)"><i class="ms-Icon ms-Icon--Delete" aria-hidden="true"></i></div>
                </div>
            </div>
            <div class="pct100 itemRow" *ngIf="symbols.length == 0">
                <em class="ms-font-l">No symbols added</em>
            </div>
        </div>
    </div>
</div>

// OfficeAddin/05 Using modern JavaScript/Demos/01 Office Add-in using React/src/components/app.tsx
import * as React from 'react';
import { MessageBar, MessageBarType, TextField, TextFieldBase } from 'office-ui-fabric-react';
import { Header } from './header';
import { Waiting } from './waiting';
import { StockItem } from './StockItem';
import { ExcelTableUtil } from '../utils/excelTableUtil';

const ALPHAVANTAGE_APIKEY: string = '{{REPLACE_WITH_ALPHAVANTAGE_APIKEY}}';

export interface AppProps {
  title: string;
}

export interface AppState {
  listItems: string[];
  waiting: boolean;
  error: string;
}

export default class App extends React.Component<AppProps, AppState> {
  newSymbol:any = React.createRef();
  tableUtil: ExcelTableUtil = new ExcelTableUtil('Portfolio', 'A1:H1', [
    'Symbol',
    'Last Price',
    'Timestamp',
    'Quantity',
    'Price Paid',
    'Total Gain',
    'Total Gain %',
    'Value'
  ]);
  constructor(props, context) {
    super(props, context);
    this.state = {
      listItems: [],
      waiting: false,
      error: ''
    };
  }

  componentDidMount() {
    // Sync stocks already in Excel table
    this.syncTable().then(() => {});
  }

  // Adds symbol
  addSymbol = async (event) => {
    if (event.key === 'Enter') {
      const element = this.newSymbol.current as TextFieldBase;
      const symbol = element.value.toUpperCase();
  
      // Get quote and add to Excel table
      this.setState({ waiting: true });
      this.getQuote(symbol).then(
        (res: any) => {
          const data = [
            res['1. symbol'], //Symbol
            res['2. price'], //Last Price
            res['4. timestamp'], // Timestamp of quote,
            0, // quantity (manually entered)
            0, // price paid (manually entered)
            '=(B:B * D:D) - (E:E * D:D)', //Total Gain $
            '=H:H / (E:E * D:D) * 100', //Total Gain %
            '=B:B * D:D' //Value
          ];
          this.tableUtil.addRow(data).then(
            () => {
              let symbols = this.state.listItems;
              symbols.unshift(element.state.value.toUpperCase());
              this.setState({ listItems: symbols });
              element.setState({ value: '' });
              this.setState({ waiting: false });
            },
            err => {
              this.setState({ error: err });
              this.setState({ waiting: false });
            }
          );
        },
        err => {
          this.setState({ error: err });
          this.setState({ waiting: false });
        }
      );
    }
  }

  // Delete symbol
  deleteSymbol = async index => {
    // Delete from Excel table by index number
    let symbols = this.state.listItems;
    let symbol = symbols[index];
    this.setState({ waiting: true });
    this.tableUtil.getColumnData('Symbol').then(
      async (columnData: string[]) => {
        // Ensure the symbol was found in the Excel table
        if (columnData.indexOf(symbol) !== -1) {
          this.tableUtil.deleteRow(columnData.indexOf(symbol)).then(
            async () => {
              symbols.splice(index, 1);
              this.setState({ listItems: symbols });
              this.setState({ waiting: false });
            },
            err => {
              this.setState({ error: err });
              this.setState({ waiting: false });
            }
          );
        } else {
          symbols.splice(index, 1);
          this.setState({ waiting: false });
        }
      },
      err => {
        this.setState({ error: err });
        this.setState({ waiting: false });
      }
    );
  }

  // Refresh symbol
  refreshSymbol = async (index: number) => {
    // Refresh stock quote and update Excel table
    let symbols = this.state.listItems;
    let symbol = symbols[index];
    this.setState({ waiting: true });
    this.tableUtil.getColumnData('Symbol').then(
      async (columnData: string[]) => {
        // Ensure the symbol was found in the Excel table
        const rowIndex = columnData.indexOf(symbol);
        if (rowIndex !== -1) {
          this.getQuote(symbol).then((res: any) => {
            // "last trade" is in column B with a row index offset of 2 (row 0 + the header row)
            this.tableUtil
              .updateCell(`B${rowIndex + 2}:B${rowIndex + 2}`, res.current)
              .then(
                async () => {
                  this.setState({ waiting: false });
                },
                err => {
                  this.setState({ error: err });
                  this.setState({ waiting: false });
                }
              );
          });
        } else {
          this.setState({ error: 'Symbol not in table' });
          symbols.splice(index, 1);
          this.setState({ waiting: false });
        }
      },
      err => {
        this.setState({ error: err });
        this.setState({ waiting: false });
      }
    );
  }

  // Reads symbols from an existing Excel workbook and pre-populates them in the add-in
  syncTable = async () => {
    this.setState({ waiting: true });
    this.tableUtil.getColumnData('Symbol').then(
      async (columnData: string[]) => {
        this.setState({ listItems: columnData });
        this.setState({ waiting: false });
      },
      err => {
        this.setState({ error: err });
        this.setState({ waiting: false });
      }
    );
  }

  // Gets a quote by calling into the stock service
  getQuote = async (symbol: string) => {
    return new Promise((resolve, reject) => {
      const queryEndpoint = `https://www.alphavantage.co/query?function=BATCH_STOCK_QUOTES&symbols=${escape(symbol)}&interval=1min&apikey=${ALPHAVANTAGE_APIKEY}`;
  
      fetch(queryEndpoint)
        .then((res: any) => {
          if (!res.ok) {
            reject('Error getting quote');
          }
          return res.json();
        })
        .then((jsonResponse: any) => {
          const quote: any = jsonResponse['Stock Quotes'][0];
          resolve(quote);
        });
    });
  }

  render() {
    const stocks = this.state.listItems.map((symbol, index) => (
      <StockItem
        symbol={symbol}
        index={index}
        onDelete={this.deleteSymbol.bind(this, index)}
        onRefresh={this.refreshSymbol.bind(this, index)}
      />
    ));
    return (
      <div className="container">
        {this.state.waiting && <Waiting />}
        <Header title={this.props.title} />
        {this.state.error != '' && (
          <MessageBar
            messageBarType={MessageBarType.error}
            isMultiline={false}
            onDismiss={() => {
              this.setState({ error: '' });
            }}>
            {this.state.error}
          </MessageBar>
        )}
        <div className="padding10">
          <div className="pct100 tbl-head">
            <span className="ms-font-l">Stock Symbols</span>
          </div>
          <div className="pct100">
            <TextField componentRef={this.newSymbol} onKeyPress={this.addSymbol.bind(this)} placeholder="Enter a stock symbol (ex: MSFT)" />
          </div>
          {stocks}
        </div>
      </div>
    );
  }
}

// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.
